title: Gerard Hager # your name (or website title) here
logo: "/images/me_crop_circle_trnsp.gif?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Curious about all things Signal Processing and Machine Learning.  Loves diving deep into any problem.
  <br><br>
  "_Suckin' at something is the first step towards being sorta good at something._
  sdflksnaflkasd"
  <br><br>
  <a href="https://www.linkedin.com/in/gerard-hager-487b30209">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
